# Generated by Django 4.1.7 on 2023-08-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BinaryField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControlModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.module')),
                ('read_command_period', models.IntegerField(default=3)),
                ('check_sensors_period', models.IntegerField(default=30)),
            ],
            bases=('configuration.module',),
        ),
        migrations.CreateModel(
            name='LoraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addh', models.CharField(default='FF', max_length=2)),
                ('addl', models.CharField(default='FF', max_length=2)),
                ('channel', models.CharField(default='64', max_length=2)),
                ('uart_parity', models.CharField(default='0', max_length=1)),
                ('uart_baud_rate', models.CharField(default='3', max_length=1)),
                ('air_data_rate', models.CharField(default='2', max_length=1)),
                ('transmission_power', models.CharField(default='0', max_length=1)),
                ('wor_period', models.CharField(default=3, max_length=1)),
                ('enable_RSSI_ambient_noise', models.BooleanField(default=False)),
                ('enable_lbt', models.BooleanField(default=False)),
                ('enable_rssi', models.BooleanField(default=True)),
                ('enable_fixed_transmission', models.BooleanField(default=True)),
                ('power_down_lose_config', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lora', to='configuration.module')),
            ],
        ),
        migrations.CreateModel(
            name='SensorModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.module')),
                ('crypt_key', models.BinaryField(max_length=8)),
                ('timeout_sensors_read_packet', models.IntegerField(default=60)),
                ('timeout_config_packet', models.IntegerField(default=60)),
                ('timeout_handshake', models.IntegerField(default=60)),
                ('timeout_SYN', models.IntegerField(default=20)),
                ('timeout_SYNACK', models.IntegerField(default=20)),
                ('timeout_ACK', models.IntegerField(default=20)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='controller', to='configuration.controlmodule')),
            ],
            bases=('configuration.module',),
        ),
    ]
