# Generated by Django 4.1.7 on 2023-08-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addh', models.IntegerField(default=0)),
                ('addl', models.IntegerField(default=0)),
                ('transmission_power', models.CharField(default='0', max_length=1)),
                ('enable_power_down_lose_config', models.BooleanField(default=False)),
                ('enable_lbt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControlModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.module')),
                ('read_command_period', models.IntegerField(default=3)),
            ],
            bases=('configuration.module',),
        ),
        migrations.CreateModel(
            name='SensorModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuration.module')),
                ('is_enable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('channel', models.IntegerField(default=64)),
                ('wor_period', models.CharField(default='3', max_length=1)),
                ('air_data_rate', models.CharField(default='2', max_length=1)),
                ('crypth', models.IntegerField(default=0)),
                ('cryptl', models.IntegerField(default=0)),
                ('timeout_sensors_read_packet', models.FloatField(default=60)),
                ('timeout_config_packet', models.FloatField(default=60)),
                ('timeout_handshake', models.FloatField(default=60)),
                ('timeout_SYN', models.FloatField(default=20)),
                ('timeout_SYNACK', models.FloatField(default=20)),
                ('timeout_ACK', models.FloatField(default=20)),
                ('auto_send_sensors_period', models.FloatField(default=10)),
            ],
            bases=('configuration.module',),
        ),
        migrations.CreateModel(
            name='ModuleObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_controller', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=models.SET('ERASED'), related_name='fk_module', to='configuration.module')),
            ],
        ),
    ]
