# Generated by Django 4.1.7 on 2023-10-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensormodule',
            name='accel_default_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalsensormodule',
            name='accel_default_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalsensormodule',
            name='accel_default_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensormodule',
            name='accel_default_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensormodule',
            name='accel_default_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensormodule',
            name='accel_default_z',
            field=models.FloatField(default=0.0),
        ),
    ]
