# Generated by Django 4.1.7 on 2023-10-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_historicalsensormodule_air_soil_moisture_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsensormodule',
            name='air_soil_moisture_value',
        ),
        migrations.RemoveField(
            model_name='historicalsensormodule',
            name='water_soil_moisture_value',
        ),
        migrations.RemoveField(
            model_name='sensormodule',
            name='air_soil_moisture_value',
        ),
        migrations.RemoveField(
            model_name='sensormodule',
            name='water_soil_moisture_value',
        ),
    ]
