# Generated by Django 4.1.7 on 2023-10-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sensor_module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.sensormodule')),
            ],
        ),
    ]
